services:
  app:
    image: docker-spring-boot-postgres:latest
    build:
      context: backend
    ports:
      - '8080:8080'
    depends_on:
      - db

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    labels:
      org.springframework.boot.service-connection: postgres

volumes:
  postgres-data:
