services:
  app:
    image: docker-spring-boot-postgres:latest
    env_file:
      - .env
    build:
      context: backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      POSTGRES_DATASOURCE: ${POSTGRES_DATASOURCE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/views.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      org.springframework.boot.service-connection: db

  # add this for simplicity and easy access to the database
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./backups:/backups

  website:
    build:
      context: ./websiteNefix
    ports:
      - '3000:3000'
    depends_on:
      - app
    environment:
      API_URL: http://localhost:8080
    volumes:
      - ./websiteNefix:/usr/src/app
volumes:
  postgres-data:
  pgadmin-data:
