version: "3.3"
services:
  postgres:
    image: postgres:latest
    build: .
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"

  # backend:
  #   build: backend
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres

volumes:
  postgres-data:

