### Get all movies
GET localhost:8080/movie

### Subtitle ###


### Get movie
GET localhost:8080/


### Create movie
POST localhost:8080/movie
Content-Type: application/json

{
    "title": "The Shawshank Redemption",
    "views": 0
}


### Get movie subtitles
GET localhost:8080/movie/1/subtitle

### Get movie subtitles by id
GET localhost:8080/movie/1/subtitle/1

### Add movie subtitles
POST localhost:8080/movie/1/subtitle
Content-Type: application/json

{
    "language": "English",
    "subtitleLocation": "http://example.com/subtitle.srt",
    "movieId": 1
}

### Delete movie subtitles by id
DELETE localhost:8080/movie/1/subtitle/1

### Update movie subtitles
PUT localhost:8080/movie/1/subtitle/10
Content-Type: application/json

{
    "language": "English or Spanish",
    "subtitleLocation": "http://example.com/subtitle-updated.srt",
    "movieId": 1
}

### Get movie subtitles
#GET localhost:8080/movie/with-subtitle


### Get movie infomovie by id
GET localhost:8080/movie/1/info-movie

### Get all infomovies
#GET localhost:8080/movie/info-movies

### Create infomovie
POST localhost:8080/movie/1/info-movie
Content-Type: application/json

{
    "description": "I am not updated",
    "type": "CLASSIFICATION"
}

### Delete infomovie
DELETE localhost:8080/movie/1/info-movie/1

### Update infomovie
PATCH localhost:8080/movie/1/info-movie/1
Content-Type: application/json

{
    "description": "I am updated"
}
